DROP DATABASE IF EXISTS RCM_db;
CREATE DATABASE RCM_db;

USE RCM_db;

CREATE TABLE department (
  id INT AUTO_INCREMENT PRIMARY KEY,
  dep_name VARCHAR(30) NOT NULL
);

CREATE TABLE role_list ( 
  id INT AUTO_INCREMENT PRIMARY KEY,
  rank VARCHAR(20) NOT NULL,
  salary VARCHAR(8) NOT NULL,
  dep_id INT UNSIGNED NOT NULL,
  CONSTRAINT fk_department FOREIGN KEY (dep_id) REFERENCES department(id) ON DELETE CASCADE
);

CREATE TABLE employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(40) NOT NULL,
  last_name VARCHAR(40) NOT NULL,
  role_id INT NOT NULL,  
  supervisor_id INT(12) NOT NULL,
  CONSTRAINT fk_role_list FOREIGN KEY (role_id) REFERENCES role_list(id) ON DELETE CASCADE,
  CONSTRAINT fk_supervisor FOREIGN KEY (supervisor_id) REFERENCES employees(id) ON DELETE SET NULL
);